config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :articles do
    resources :comments
  end
  resources :contacts
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do  
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 5 }
    
    belongs_to :user, optional: true
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :article, optional: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
 validates_presence_of :name
 validates_presence_of :email
 validates_presence_of :message
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :articles
 has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
    @last_five_articles = Article.last(5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.new(params[:comment].permit(:body))
        @comment.user_id = current_user.id if current_user
        
        if @comment.save
            redirect_to article_path(@article), notice: "Your comment has been saved."
        else
            redirect_to 'new'
        end
    end
    
    def update
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        
        if @comment.update(params[:comment].permit(:body))
           redirect_to article_path(@article), notice: "Your comment has been updated."
        else
           render 'edit'
        end
    end
    
    def edit
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
    end
    
    def show
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), notice: "Your comment has been deleted."
    end
    

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

 def new
  @contact = Contact.new
 end

 def create
   @contact = Contact.new(contact_params)
   
    if @contact.save
       redirect_to root_path
       name = params[:contact][:name]
       email = params[:contact][:email]
       message = params[:contact][:message]
       ContactMailer.contact_email(name, email, message).deliver
       flash[:success] = "Thanks for the message, we will be in touch soon."
    else
      redirect_to pages_contact_path
      flash[:danger] = "Opps, there was a problem! Please fill out all the fields."
    
    end
 end




 private

 def contact_params
 params.require(:contact).permit(:name, :email, :message)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  def index
    if current_user
      redirect_to articles_path
    end
    @articles = Article.last(5)
  end

  def contact
    @contact = Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 private
 def sign_up_params
  params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :username,
    :firstname,
    :lastname
    )
 end
 def account_update_params
  params.require(:user).permit(
   :email,
   :password,
   :password_confirmation,
   :current_password,
   :username,
   :firstname,
   :lastname
 )
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>
 

</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="row">
 <!-- Blog article Content Column -->
 <div class="col-lg-8">
 <% @articles.each do |article| %>
 <!-- Blog article -->
 <!-- Title -->
  <h4 style="font-size: 45.5px;"><%= link_to article.title, article %></h4>
 <!-- Author -->
  <p>
   Article By:<strong> <%= article.user.username %></strong>
  </p>
  <hr>
 <!-- articleed Comments -->
 <!-- Comment -->
  <% end %>
  <%= link_to "New article", new_article_path, class: "btn btn-default btn-xs" %>
 </div>
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">
  <div class="well">
   <h4>Recent articles</h4>
   <% @last_five_articles.each do |a| %>
    Created by: <%= a.user.username %><br />
    <strong><%= link_to a.title, a %></strong>
    <p><%= truncate(a.body) %></p>
   <% end %>
  </div>
 </div>
</div>
<%= will_paginate @articles %>
<br>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<div class="row">
 <!-- Blog Post Content Column -->
 <div class="col-lg-8">
 <!-- Blog Post -->
 <!-- Title -->
   <h1 style="font-size: 3.9rem;"> 
     <%= @article.title %>
   </h1>
 <!-- Author -->
    <p class="lead">
     <%= @article.user.username %>
    </p>
 <hr>
 <!-- Post Content -->
  <%= @article.body %>
 <hr>
 <!-- Blog Comments -->
 <%= render @article.comments %>
 <!-- Comments Form -->
  
 <%= render 'comments/form' %>
 
 <hr>
 <!-- Posted Comments -->
 <!-- Comment -->
 </div>
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">

 </div>
</div>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/comments/_comment.html.erb
 <div class="media">
  <div class="pull-left">
   
   <%= comment.user.username %>
  
  </div>
  <div class="media-body">
   <p class="media-heading pull-right">
    <%= time_ago_in_words(comment.created_at) %>
   </p><br />
   <%= comment.body %>
  </div>
 </div>
<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>
<%= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %>

<%= f.input :body%>
<%= f.submit "Post your comment" %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>

<%= simple_form_for([@article, @comment]) do |f| %>
<%= f.input :body %>
<%= f.submit %>
<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-fixed-bottom">
  <div class="footer-right">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fa-brands fa-twitter"></i></a>
    <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
    <a href="#"><i class="fa-brands fa-github"></i></a>
  </div>
  <div class="footer-left">
    <p class="footer-links">
    ·
    <%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
    ·
    <%= link_to "About Us", pages_about_path, class: "page-scroll" %>
    ·
    </p>
    <p> </p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <h1><%= link_to "Zvone's Articles", root_path, class: 'nav navbar-nav' %></h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        
        
        
      </ul>
      <ul class="nav navbar-nav navbar-right justify-content-end">
        
        
        <li><%= link_to "Contact Us",  pages_contact_path %></li>
        <li><%= link_to "About Us",  pages_about_path %></li>
        <li><%= link_to "View Article",  articles_path %></li>
        
        <% if !current_user %>
        <li><%= link_to "Sign Up",  new_user_registration_path %></li>
        <li><%= link_to "Sign In",  new_user_session_path %></li>
        
      </ul>
      <% else %> 
      <div class="dropdown">
        <button class="btn btn-secondary btn-lg dropdown-toggle"  type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.username %>
        </button>
        <ul id="a" class="dropdown-menu dropdown-menu-dark btn-lg" aria-labelledby="dropdownMenuButton2">
          <li><a class="dropdown-item active" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><%= link_to "Edit My Profile",  edit_user_registration_path %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zvone's Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= bootstrap_flash %>
    
    
     
    <div class='container'>
      
      <%= yield %>
    </div>
    
    <%= render 'layouts/foot' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   
  </body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
             <%= simple_form_for @contact do |f| %>
             <%= f.input :name %>
             <%= f.input :email %>
             <%= f.input :message %>
             <%= f.submit "Get in touch!", class: "btn btn-info" %>
             <% end %>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>About Us</h1>
    <p class="lead">Test Text</p>
    <ul class="list-unstyled">
      <li>List Item</li>
      <li>List Item 2</li>
    </ul>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Contact Us</h1>
    <p class="lead">Test Text</p>
    <ul class="list-unstyled">
      <li>List Item</li>
      <li>List Item 2</li>
    </ul>
  </div>
  <%= render 'pages/mailer' %>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-8">
 <!-- Blog Post -->
 <!-- Title -->
    <div class="jumbotron">
      <h1>Welcome to Zvone's Articles. </h1>
      <p>Awesome applications built with Rails!</p>
      <p></p>
    </div>
  </div>
 <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
 <!-- Blog Categories Well -->
 <!-- Side Widget Well -->
    <div class="well">
      <h4>Recent Posts</h4>
      <% @articles.each do |a| %>
      Created by: <%= a.user.username %><br />
      <strong><%= link_to a.title, a %></strong>
      <p><%= truncate(a.body) %></p>
      <% end %>
    </div>
  </div>
</div>
<!-- /.row -->
<hr>